environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm rm --save-dev connect-redis
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"